from enum import Enum


class MessageType(str, Enum):
    TRAFFIC_UPDATE = "TRAFFIC_UPDATE"
    NEGOTIATION_START = "NEGOTIATION_START"
    COMMITMENT_PROPOSAL = "COMMITMENT_PROPOSAL"
    COMMITMENT_RESPONSE = "COMMITMENT_RESPONSE"
    COMMITMENT_BROADCAST = "COMMITMENT_BROADCAST"
    VIOLATION_REPORT = "VIOLATION_REPORT"
    OTHER = "OTHER"
    RECEIVED = "RECIEVED"


class CommitmentType(str, Enum):
    EARLY_EXIT = "EARLY_EXIT"
    LATE_EXIT = "LATE_EXIT"
    STAGGERED_EXIT = "STAGGERED_EXIT"
    CUSTOM = "CUSTOM"
